spring.application.name=CampusMarketplace

# H2 in-memory DB (swap datasource url/driver for MySQL/PostgreSQL in prod)
spring.datasource.url=jdbc:h2:file:./data/marketplace;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html

server.port=8080
server.error.whitelabel.enabled=false
